apache/datasketches-cpp

- common/include/serde.hpp
- fi/fi.mk
- fi/include/frequent_items_sketch.hpp
- fi/include/reverse_purge_hash_map.hpp
- kll/include/kll_helper.hpp
- kll/include/kll_quantile_calculator.hpp
- kll/include/kll_sketch.hpp
- kll/kll.mk
- kll/test/kll_sketch_test.cpp
comparator and serde as template params
> KLL refactoring

- theta/include/theta_sketch.hpp
- theta/include/theta_sketch_impl.hpp
> fixed cur and nom order

- theta/include/theta_intersection_impl.hpp
> Theta intersection fix

- hll/include/HllUnion-internal.hpp
> ooo flag fix

- NOTICE
- README.md
- common/include/memory_operations.hpp
- kll/include/kll_sketch.hpp
- python/README.md
- sampling/include/var_opt_sketch.hpp
- sampling/include/var_opt_union.hpp
- update build instructions
- update notice file to remove cppunit and add catch2
- add documentation to varopt
- remove unnecessary cast in memory_operations
- add missing parameter in kll_sketch documentation
> documentation updates (mostly)

- common/include/serde.hpp
No tests associated with the change, but this should let us properly add tests of corrupted streams
> Serde exception

- .gitignore
- LICENSE
- NOTICE
Please double check the License file if we are still using all the 3rd
party licenses.
> Updated License, Notice, gitignore

- sampling/include/var_opt_sketch_impl.hpp
- sampling/include/var_opt_union_impl.hpp
no more asserts, and fixed a few comment typos in the process
> convert asserts to if/throw std::logic_error in varopt

- .github/workflows/code_coverage.yml
- CMakeLists.txt
The new coverage workflow will only run on PRs. Creating one since we'll need to merge eventually, but also in hopes of triggering it to run in the meantime.
> Code coverage

- theta/include/theta_intersection_impl.hpp
- theta/include/theta_sketch_impl.hpp
- theta/include/theta_union_impl.hpp
> MSVC compatibility

- .github/workflows/code_coverage.yml
i don't think we'll know if this actually works until we merge it
> try to get coveralls to have a useful badge

- README.md
- python/README.md
- setup.py
Add the Apache name where applicable in readmes
> Add Apache branding to mentions of Datassketches

- .github/workflows/code_coverage.yml
- common/include/common_defs.hpp
- cpc/include/cpc_sketch_impl.hpp
- fi/include/frequent_items_sketch_impl.hpp
- hll/include/AuxHashMap-internal.hpp
- hll/include/CouponHashSet-internal.hpp
- hll/include/CouponList-internal.hpp
- hll/include/HllArray-internal.hpp
- kll/include/kll_sketch_impl.hpp
- req/include/req_compactor_impl.hpp
- sampling/include/var_opt_sketch_impl.hpp
- sampling/include/var_opt_union_impl.hpp
- theta/include/theta_sketch_impl.hpp
- tuple/include/array_of_doubles_sketch_impl.hpp
- tuple/include/tuple_sketch_impl.hpp
Simplified and unified serialization and deserialization except HLL, where it is quite different form everything else, and will take a separate effort.
> Unify serialization

- kll/include/kll_quantile_calculator_impl.hpp
> Late initialization of iterator in kll sketch

- kll/include/kll_sketch_impl.hpp
- kll/test/kll_sketch_test.cpp
> fixed iterator

- common/include/MurmurHash3.h
> fixed misaligned access

- theta/include/theta_update_sketch_base.hpp
- theta/include/theta_update_sketch_base_impl.hpp
> exception safety

- CMakeLists.txt
not using this yet, but it'll let us add CI jobs eventually
> Add SANITIZE option to cmake to support sanitization

- python/src/theta_wrapper.cpp
- theta/include/theta_jaccard_similarity_base.hpp
- theta/test/theta_jaccard_similarity_test.cpp
> added seed

- theta/include/theta_intersection.hpp
- theta/include/theta_union.hpp
- theta/include/theta_union_base_impl.hpp
- theta/include/theta_union_impl.hpp
- theta/include/theta_update_sketch_base_impl.hpp
- fixed union base (I think this bug could lead to slightly incorrect results in rare circumstances)
- minor cleanup and slight performance improvement
> Theta fix and cleanup

- common/include/conditional_forward.hpp
> no move if const_iterator

- fi/include/frequent_items_sketch_impl.hpp
- kll/include/kll_sketch_impl.hpp
- kll/test/kll_sketch_test.cpp
> Fix issue 236

- python/README.md
Removed .gitmodules since we no longer have a dependent module, and rewrote a bunch of the python readme.
> update python readme, remove unused .gitmodules

- hll/include/HllSketch-internal.hpp
> fixed HLL to_string()

- CMakeLists.txt
- README.md
- cmake/DataSketchesConfig.cmake.in
Addressing some of @jmalkin's comments on the last PR by updating the documentation (including fixing some whitespace issues). Also, fixing a couple of the exported variables so that they actually have values populated correctly.
> Updating documentation and fixing definition of exported variables

- theta/include/compact_theta_sketch_parser_impl.hpp
- theta/include/theta_sketch_impl.hpp
- theta/test/theta_sketch_test.cpp
Reuse parser in deserialize from bytes.
This should also add support of serial versions 1 and 2, which was missing in deserialize from bytes.
> Theta: common code for wrap and deserialize

- hll/test/HllSketchTest.cpp
Added a few tests. One of them would have caught the bug fixed by #266
> serialize-deserialize-serialize tests

- fi/include/frequent_items_sketch.hpp
- fi/include/frequent_items_sketch_impl.hpp
- fi/test/frequent_items_sketch_custom_type_test.cpp
- kll/include/kll_sketch.hpp
- kll/include/kll_sketch_impl.hpp
- kll/test/kll_sketch_test.cpp
- python/src/fi_wrapper.cpp
- req/include/req_sketch.hpp
- req/include/req_sketch_impl.hpp
- sampling/include/var_opt_sketch.hpp
- sampling/include/var_opt_sketch_impl.hpp
- sampling/include/var_opt_union.hpp
- sampling/include/var_opt_union_impl.hpp
- sampling/test/var_opt_allocation_test.cpp
- tuple/include/tuple_sketch.hpp
deprecated class-level serde (to be removed later), support serde instance
> Serde instance

- quantiles/include/quantiles_sketch.hpp
- quantiles/include/quantiles_sketch_impl.hpp
- quantiles/test/kolmogorov_smirnov_test.cpp
- quantiles/test/quantiles_sketch_test.cpp
> Quantile type conversion

- python/README.md
With luck these instructions will be a little more clear
> try to improve python readme

- cpc/include/cpc_compressor_impl.hpp
> check pseudo phase

- fi/include/frequent_items_sketch.hpp
- fi/include/frequent_items_sketch_impl.hpp
- fi/test/frequent_items_sketch_custom_type_test.cpp
- sampling/include/var_opt_sketch.hpp
- sampling/include/var_opt_sketch_impl.hpp
- sampling/include/var_opt_union.hpp
- sampling/include/var_opt_union_impl.hpp
- sampling/test/var_opt_allocation_test.cpp
- sampling/test/var_opt_sketch_test.cpp
- sampling/test/var_opt_union_test.cpp
removed serde from class template
> No class level serde

- tuple/test/CMakeLists.txt
- tuple/test/engagement_test.cpp
C++ version of Lee's [engagement test](https://github.com/apache/datasketches-java/blob/master/src/test/java/org/apache/datasketches/tuple/aninteger/EngagementTest.java)
> Engagement test

- tuple/include/tuple_sketch_impl.hpp
similar to #303 for Tuple sketch
> serialization fix

- common/include/quantile_sketch_sorted_view.hpp
- common/include/quantile_sketch_sorted_view_impl.hpp
- common/test/quantile_sketch_sorted_view_test.cpp
- kll/include/kll_sketch.hpp
- kll/include/kll_sketch_impl.hpp
- kll/test/kll_sketch_custom_type_test.cpp
- kll/test/kll_sketch_test.cpp
- quantiles/include/quantiles_sketch.hpp
- quantiles/include/quantiles_sketch_impl.hpp
- quantiles/test/quantiles_compatibility_test.cpp
- quantiles/test/quantiles_sketch_test.cpp
- req/include/req_compactor.hpp
- req/include/req_compactor_impl.hpp
- req/include/req_sketch.hpp
- req/include/req_sketch_impl.hpp
- req/test/req_sketch_custom_type_test.cpp
also noticed that we did not have get_allocator() in some sketches, and added that
> comparator instance support

- fi/include/frequent_items_sketch.hpp
- fi/include/frequent_items_sketch_impl.hpp
- fi/include/reverse_purge_hash_map.hpp
- fi/include/reverse_purge_hash_map_impl.hpp
- fi/test/frequent_items_sketch_custom_type_test.cpp
- fi/test/reverse_purge_hash_map_test.cpp
- kll/include/kll_sketch.hpp
- quantiles/include/quantiles_sketch.hpp
- req/include/req_sketch.hpp
also fixed docs in KLL, REQ and Quantiles with respect to SerDe
> Equal to instance

- tuple/test/engagement_test.cpp
> removed unused variables

- cpc/include/cpc_confidence.hpp
- hll/include/HllArray-internal.hpp
- hll/include/HllUtil.hpp
> HlLL get_rel_err() fix

- CMakeLists.txt
- count/CMakeLists.txt
- count/include/count_min.hpp
- count/include/count_min_impl.hpp
- count/test/CMakeLists.txt
- count/test/count_min_test.cpp
An initial attempt at cpp count min sketch.
Specific feedback that might be helpful:
- `get_sketch()` would this be better as an iterator over the sketch table, rather than returning the table explicitly?
- There is a danger of the hash seed addition overflowing.  See `count_min_impl.hpp` lines 24 & 115.  Is this problematic as it is passed as input to murmurhash?
> Cpp countmin

- count/include/count_min.hpp
- count/include/count_min_impl.hpp
Changed the family id to 18 as per [issue: # 359](https://github.com/apache/datasketches-cpp/issues/359)
> Changed family id to 18

- common/include/memory_operations.hpp
- density/include/density_sketch.hpp
- density/include/density_sketch_impl.hpp
- density/test/density_sketch_test.cpp
- python/datasketches/DensityWrapper.py
- python/src/density_wrapper.cpp
- python/tests/density_test.py
> Density serialization

- common/test/test_allocator.hpp
avoid casting to and from char
> better test allocator

- common/include/quantiles_sorted_view_impl.hpp
- count/include/count_min.hpp
- count/include/count_min_impl.hpp
- count/test/count_min_allocation_test.cpp
- count/test/count_min_test.cpp
- kll/include/kll_sketch_impl.hpp
- quantiles/include/quantiles_sketch_impl.hpp
- req/include/req_sketch_impl.hpp
- req/test/req_sketch_test.cpp
- theta/include/bit_packing.hpp
- theta/include/theta_helpers.hpp
- theta/include/theta_sketch_impl.hpp
- tuple/test/engagement_test.cpp
some style changes as well to be consistent throughout the library
> Avoid warnings

- common/CMakeLists.txt
- kll/include/kll_sketch.hpp
- kll/include/kll_sketch_impl.hpp
- quantiles/include/quantiles_sketch.hpp
- quantiles/include/quantiles_sketch_impl.hpp
- quantiles/test/quantiles_sketch_test.cpp
switched from pointers to optional, added missing moves in merge
> use optional to improve the code

- sampling/test/CMakeLists.txt
missed this when merging changes
> Un-break serialization test builds

- README.md
Partial fix for DATASKETCHES-13
> [DATASKETCHES-13] Update README.md

- CMakeLists.txt
- CODE_OF_CONDUCT.md
- filters/include/bloom_filter.hpp
- filters/test/bloom_filter_test.cpp
- hll/include/CubicInterpolation-internal.hpp
- hll/include/HllArray-internal.hpp
- hll/test/HllSketchTest.cpp
- hll/test/HllUnionTest.cpp
- quantiles/include/quantiles_sketch.hpp
- quantiles/include/quantiles_sketch_impl.hpp
- sampling/include/var_opt_sketch_impl.hpp
- sampling/include/var_opt_union_impl.hpp
- sampling/test/ebpps_allocation_test.cpp
- sampling/test/ebpps_sketch_test.cpp
- sampling/test/var_opt_allocation_test.cpp
> Typo fixes
