hll/include/HllSketch-internal.hpp, hll/test/HllUnionTest.cpp
I don't have a gcc-compatible cppunit, but I think this should fix the private access issue that broke the unit tests (which were using only the public API!)
=> change another location to placement new, restore unit tests

MANIFEST.in, pyproject.toml, python/src/cpc_wrapper.cpp, python/src/fi_wrapper.cpp, python/src/hll_wrapper.cpp, python/src/kll_wrapper.cpp, setup.py
I believe this gets everything ready to create a source distribution (sdist) tarball for python. But I'm not sure if there's an issue packaging the BSD-licensed pybind11 in the tarball with our code?
We point to it as a submodule in git, which they suggest doing in their own cmake example, and they even say to use --recursive when cloning. But that's not necessarily the same as distributing it within our tarball.
Since the current code doesn't work properly to create an artifact that can be pushed to python's package repository (pypi) I'm ok with it. But committing this change would make it much easier to upload something to there. So I'll suggest hold off on actually merging until we get feedback on whether this approach is valid.
=> Python distribution

common/include/serde.hpp, common/test/A.hpp, fi/fi.mk, fi/test/CMakeLists.txt, fi/test/frequent_items_sketch_custom_type_test.cpp, kll/include/kll_helper.hpp, kll/include/kll_quantile_calculator.hpp, kll/include/kll_sketch.hpp, kll/kll.mk, kll/test/CMakeLists.txt, kll/test/kll_sketch_custom_type_test.cpp, kll/test/kll_sketch_test.cpp, kll/test/kll_sketch_validation.cpp
- no default construction of objects of type T
- always use given allocator
- update(T&& value) method to move input values into a sketch if possible
=> KLL sketch improvements

hll/include/AuxHashMap.hpp, hll/include/CouponHashSet-internal.hpp, hll/include/CouponHashSet.hpp, hll/include/CouponList-internal.hpp, hll/include/CouponList.hpp, hll/include/Hll4Array-internal.hpp, hll/include/Hll4Array.hpp, hll/include/Hll6Array-internal.hpp, hll/include/Hll6Array.hpp, hll/include/Hll8Array-internal.hpp, hll/include/Hll8Array.hpp, hll/include/HllArray-internal.hpp, hll/include/HllArray.hpp, hll/include/HllSketch-internal.hpp, hll/include/HllSketchImpl-internal.hpp, hll/include/HllSketchImpl.hpp, hll/include/HllSketchImplFactory.hpp, hll/include/HllUnion-internal.hpp, hll/include/HllUtil.hpp, hll/include/PairIterator.hpp, hll/include/hll.hpp, hll/test/CouponHashSetTest.cpp, hll/test/CouponListTest.cpp, hll/test/CrossCountingTest.cpp, hll/test/HllArrayTest.cpp, hll/test/HllSketchTest.cpp, hll/test/HllUnionTest.cpp, hll/test/ToFromByteArrayTest.cpp, python/src/hll_wrapper.cpp
I think I got the public portions of hll.hpp changed. This can be extended to that whole file if we think it's warranted.
=> change HLL public API from CamelCase to lower_with_underscore

common/include/MurmurHash3.h, cpc/include/common.h, cpc/include/cpc_sketch.hpp, cpc/include/cpc_union.hpp, cpc/src/fm85.cpp, cpc/src/fm85Compression.cpp, fi/include/reverse_purge_hash_map.hpp, kll/include/kll_sketch.hpp, theta/include/binomial_bounds.hpp
Windows does not have the following things defined:
- `u_int8_t` and alikes: use the standard C defines `uint8_t` and alikes
- `sys/time.h`: not needed as far as I can see
- and/or keywords: provided by a header
- bzero: use memset instead, its cross-platform
=> Fix windows compilation with MSVC 14 (VS 2015)

cpc/test/compression_test.cpp
Hello,
I ran into an issue when running the tests for the library. It seems just a simple include missing from a test.
```...
[ 54%] Building CXX object cpc/test/CMakeFiles/cpc_test.dir/compression_test.cpp.o
/data/fork-datasketch/cpc/test/compression_test.cpp: In member function ‘void datasketches::compression_test::compress_and_uncompress_pairs()’:
/data/fork-datasketch/cpc/test/compression_test.cpp:51:5: error: ‘sort’ is not a member of ‘std’
std::sort(pairArray, &pairArray[N]);
^
cpc/test/CMakeFiles/cpc_test.dir/build.make:88: recipe for target 'cpc/test/CMakeFiles/cpc_test.dir/compression_test.cpp.o' failed
make[2]: *** [cpc/test/CMakeFiles/cpc_test.dir/compression_test.cpp.o] Error 1
CMakeFiles/Makefile2:285: recipe for target 'cpc/test/CMakeFiles/cpc_test.dir/all' failed
make[1]: …
```
=> Add missing include in CPC compression test

.gitmodules
also moves to latest pybiind version
note that python tests won't work for this branch in isolation since it's based on master, without the frequent items python fix
=> include pybind via https rather than ssh

fi/include/frequent_items_sketch.hpp, fi/include/frequent_items_sketch_impl.hpp, fi/include/reverse_purge_hash_map.hpp, fi/include/reverse_purge_hash_map_impl.hpp, fi/test/frequent_items_sketch_custom_type_test.cpp
This will allow changing the type for weights from uint64_t. For instance, something smaller such as uint32_t or float.
=> frequent items weight type as a template parameter

cpc/include/cpc_sketch.hpp, cpc/include/cpc_union.hpp, kll/include/kll_sketch.hpp
forgot to remove this a while ago when switched to standard && and || operators
=> this should not be needed anymore

theta/include/theta_union_impl.hpp
if num_keys == 0, we were passing nullptr to the returned sketch, but the keys array was never freed.
=> fix memory leak in theta_union::get_result()

cpc/include/cpc_union_impl.hpp, cpc/test/cpc_sketch_test.cpp, fi/include/reverse_purge_hash_map_impl.hpp, fi/test/frequent_items_sketch_test.cpp, hll/test/CouponListTest.cpp
i believe this gives us a clean bill of health from valgrind
the only remaining memory in use now should be the cpc tables, and that's very intentional.
=> Memory fixes

fi/include/frequent_items_sketch_impl.hpp, fi/include/reverse_purge_hash_map_impl.hpp
Apply fmix64 from murmur3 on top of the given hash function to reduce reliance on its quality. For instance, the default std::hash for arithmetic types is quite poor.
=> FI use fmix64

common/CMakeLists.txt, common/include/memory_operations.hpp, common/include/serde.hpp, common/test/test_type.hpp, cpc/include/cpc_sketch_impl.hpp, fi/include/frequent_items_sketch_impl.hpp, hll/include/CompositeInterpolationXTable-internal.hpp, hll/include/CompositeInterpolationXTable.hpp, hll/include/HllArray-internal.hpp, hll/include/HllUnion-internal.hpp, hll/include/HllUtil.hpp, hll/include/hll.hpp, hll/test/HllUnionTest.cpp, kll/include/kll_sketch_impl.hpp, python/src/hll_wrapper.cpp, python/tests/hll_test.py, sampling/include/var_opt_sketch.hpp, sampling/include/var_opt_sketch_impl.hpp, sampling/include/var_opt_union_impl.hpp, sampling/test/var_opt_sketch_test.cpp, sampling/test/var_opt_union_test.cpp, theta/include/theta_sketch.hpp, theta/include/theta_sketch_impl.hpp
- add memory_operations.hpp
- ensure we're checking bounds on deserialization for all sketch types
- ensure sketches that take arbitrary types can check bounds on serialize
=> Check buffer bounds

CMakeLists.txt, sampling/include/var_opt_sketch.hpp, sampling/include/var_opt_sketch_impl.hpp
- address signed/unsigned compiler warnings
- fix segfaults from copying/destroying objects in the gap
=> Sampling cleanup

theta/include/theta_a_not_b_impl.hpp, theta/include/theta_intersection.hpp, theta/include/theta_intersection_impl.hpp, theta/include/theta_sketch.hpp, theta/include/theta_sketch_impl.hpp, theta/include/theta_union_impl.hpp
sketch and union update speed is the same, sketch uses 16 more bytes of memory
=> use vector to simplify and improve safety

kll/include/kll_sketch.hpp, kll/include/kll_sketch_impl.hpp, kll/test/kll_sketch_test.cpp
=> kll: check for NaN on update with floating point types

cpc/include/cpc_sketch_impl.hpp, fi/include/frequent_items_sketch_impl.hpp, hll/include/CouponHashSet-internal.hpp, hll/include/CouponList-internal.hpp, hll/include/HllArray-internal.hpp, kll/include/kll_sketch_impl.hpp, sampling/include/var_opt_sketch_impl.hpp, sampling/include/var_opt_union_impl.hpp, theta/include/theta_sketch_impl.hpp
This might not work properly if custom serdes try using the >> operator to read strings, but that seems rather fragile for reading an array of things anyway. Maybe we should have an explicit comment in the serde header, though?
=> check istream status before returning from deserialize

.github/workflows/build_cmake.yml, python/README.md, setup.py
- rewrite python instructions to start referring to the official release packages
- add developer instructions to python README.md
- fix python version baseline to a real version snapshot rather than 0.0.1
- remove outdated comment from CI build script
=> rewrite python instructions

sampling/include/var_opt_sketch.hpp, sampling/include/var_opt_sketch_impl.hpp, sampling/include/var_opt_union.hpp, sampling/include/var_opt_union_impl.hpp, sampling/test/var_opt_union_test.cpp
I also played with to_string() a bit -- there's an internal one that gives a bit more info and the public one that uses the iterator. I'm fine killing the private one and hacking something manually if debugging in the future.
Had to either add a private iterator or basically re-implement the same logic.  The const_iterator is the only public one. The non-moving merge does use the non-const iterator for part of the merge (without explicitly invoking std::move). If that seems at all unsafe I can roll back that part.
=> Varopt move update()

python/tests/kll_test.py
I adapted the existing unit tests for the Python kll_sketch class to work for the new array-compatible kll_sketches class.  Note that some tests were unable to be adapted because they are not implemented (merging, and comparing the normalized_rank_error method result to the get_normalized_rank_error static method result).
=> Added unit tests for Python kll_sketches

.github/workflows/code_coverage.yml
Rename the "Coveralls" step to "Post to Coveralls" to better describe what happens.
=> Small workflow change

common/include/serde.hpp, kll/include/kll_sketch_impl.hpp
The motivation behind this change is that I recently started integrating
DataSketches KLL into Apache Impala and our Clang tidy build showed some issues
where c-style casts were used to remove const-ness of variables.
=> Issue-165: Remove c-style const casts from kll/ and common directories

kll/include/kll_quantile_calculator.hpp, kll/include/kll_quantile_calculator_impl.hpp, kll/include/kll_sketch_impl.hpp
The Quantile Calculator makes a temporary copy of all retained items in the sketch, merges sorted levels and assigns cumulative weight to retained items. The current implementation was designed (in Java) to copy items, and was incorrectly modified to do moves. The problem did not affect integral types, but might lead to incorrect behavior or crash for some other types depending on the types internal implementation. The proposed change should mitigate the problem.
=> KLL merge blocks fix

cpc/include/cpc_sketch_impl.hpp
I recently started integrating DataSketches CPC into Apache Impala and our Clang tidy build showed some issues
where c-style casts were used to remove const-ness of variables. like [Issue-165](https://github.com/apache/incubator-datasketches-cpp/issues/165).
centos: unit tests passed.
=> Remove c-style const casts from cpc directories

theta/include/theta_sketch_impl.hpp
I recently started integrating DataSketches Theta into Apache Impala and our Clang tidy build showed some issues
where c-style casts were used to remove const-ness of variables.
=> Remove c-style const casts from theta directories

theta/include/theta_union.hpp
Integrating DataSketches Theta into Apache Impala and  compile error：
/path/theta_union.hpp:27:10: fatal error: theta_sketch.hpp: No such file or directory
#include <theta_sketch.hpp>
=> fix include  problem

hll/CMakeLists.txt, tuple/CMakeLists.txt
The changes in this pull request were necessary to build bryanherger/vertica-datasketch after I added Hll sketch type as a UDAF.
=> Fix some CMake include file issues

kll/include/kll_sketch.hpp, kll/include/kll_sketch_impl.hpp, kll/test/kll_sketch_test.cpp, python/CMakeLists.txt, python/README.md, python/src/datasketches.cpp, python/src/kll_wrapper.cpp, python/src/req_wrapper.cpp, python/tests/kll_test.py, python/tests/req_test.py, setup.py
Add python wrapper and tests for new req sketch. 
Also discovered that kll had no get_k() method, so added that and included it in the python wrapper.
=> Req python

cpc/include/icon_estimator.hpp
Integrating DataSketches CPC to Impala, when compiling with -ASan parameter, the following error is displayed:
...
In file included from /home/impdev/Impala/be/src/exprs/datasketches-common.cc:22:
In file included from /home/impdev/Impala/be/src/thirdparty/datasketches/cpc_sketch.hpp:309:
In file included from /home/impdev/Impala/be/src/thirdparty/datasketches/cpc_sketch_impl.hpp:32:
/home/impdev/Impala/be/src/thirdparty/datasketches/icon_estimator.hpp:248:15: error: unused function 'compute_icon_estimate' [-Werror,-Wunused-function]
static double compute_icon_estimate(uint8_t lg_k, uint64_t c) {
^
1 error generated.
=> Fix unused function compile issues

common/include/MurmurHash3.h, common/test/CMakeLists.txt, common/test/integration_test.cpp, cpc/include/cpc_util.hpp, theta/include/theta_update_sketch_base.hpp
Fixes #199, although I don't know a clean way to have a test for it. It did work when I tried a local test.
Not sure if the definition belongs in Murmurhash3 or if common_defs is more appropriate? Happy to relocate as needed.
=> single compute_seed_hash implementation

theta/include/theta_intersection.hpp, theta/include/theta_intersection_impl.hpp
Some early development version of the intersection base expected a value from an intersection policy. At some point during development this was changed to void, but this policy in the Theta sketch still returns a value in a void context. It does not affect the result, but potentially is more costly and a bit confusing.
=> changed policy to return void

python/tests/kll_test.py, python/tests/req_test.py, python/tests/vector_of_kll_test.py
Expanded test margins for relative accuracy python tests by about 50%, for all provided variants of quantiles sketches.
The original margins are generally ok, but we're using random data in the tests (which also function as documentation/tutorials) and don't have a way to make the structures deterministic even for testing. As a result, we end up with the expected real-world "failures" due to low probability events showing up eventually. We have enough independent tests that it's not surprising that one of them is outside the stated tolerance every so often.
The non-quantiles sketches do not have this issue and are unchanged.
=> adjust python test tolerances

python/README.md
Fixes a small typo in the README.md to avoid confusion
=> Fix typo in python/README.md

python/src/count_sketch.py, python/src/streaming_heap.py, python/tests/count_sketch_test.py
Added a python implementation of count sketch for frequency estimation and heavy hitter detection.
=> Added count sketch

LICENSE, pyproject.toml, python/README.md, setup.py
* Improve project short description
* Add logo to long description
* Add content type so long description is parsed as markdown
* Remove unnecessary pybind11 install dependency
* Add pybind11 to LICENSE (noting only in convenience binaries)
* Add explicit mention of pybind11 and its license to python readme
=> Python cleanup

theta/include/theta_sketch.hpp, theta/include/theta_sketch_impl.hpp, theta/test/theta_sketch_test.cpp
Introducing a base_theta_sketch_alloc as a base class and moving most
methods to that class, except for iterators, so that
wrapped_compact_theta_sketch can inherit from the same base class as the
rest of the sketch methods, and thus have the same API.
=> Restructuring theta so that wrapped compact has standard methods

kll/include/kll_sketch.hpp, kll/include/kll_sketch_impl.hpp, kll/test/kll_sketch_test.cpp, python/src/kll_wrapper.cpp, python/src/req_wrapper.cpp, req/include/req_sketch.hpp
This is to support inclusive get_rank(), get_PMF() and get_CDF() inspired by the implementation of REQ sketch.
Support of inclusive get_quantile() and get_quantiles() will be done separately by reusing the quantiles calculator from the REQ sketch.
=> KLL inclusive rank

common/include/kolmogorov_smirnov.hpp, common/include/kolmogorov_smirnov_impl.hpp, python/CMakeLists.txt, python/README.md, python/src/datasketches.cpp, python/src/kll_wrapper.cpp, python/src/ks_wrapper.cpp, python/tests/kll_test.py, python/tests/quantiles_test.py, req/include/req_sketch.hpp, req/include/req_sketch_impl.hpp
Mostly KS related changes, including updating documentation to reflect it applies to KLL or classic quantiles
Also:
* Updated Python docs to include new quantiles sketch classes (while noting it's obsolete)
* Added `get_comparator()` to REQ for consistency
=> Add KS Test to python, updating docs where appropriate

kll/include/kll_helper_impl.hpp, kll/include/kll_sketch.hpp, kll/include/kll_sketch_impl.hpp
&array[index] can have undefined behavior if index == size to obtain an equivalent of the end iterator
=> KLL cleanup

NOTICE
a bunch of documentation taken from java pre-dates the cpp repo, so keeping the 2015 copyright start date
=> update NOTICE to align with java. 

hll/include/Hll4Array-internal.hpp
The type of `newShiftedVal` is uint8_t, so the condition `newShiftedVal < 0` is always false.
=> fix comparison bug since type uint8_t is always non-negative

pyproject.toml, python/README.md, python/pybind11Path.cmd
Remove pip as a build-system dependency in pyproject.toml to fix ci failure on Windows.
* Simplify pybind11Path.cmd to not require pip in favor of using pybind11's python method get_cmake_dir()
* incidental typo fix in README.md
The pyproject.toml build-system dependency on pip causes the following error when run on Windows (during the python tests) e.g.:
```
ERROR: To modify pip, please run the following command:
D:\a\datasketches-cpp\datasketches-cpp\.tox\py3\Scripts\python.EXE -m pip install --ignore-installed --no-user --prefix C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-izfez3j3\overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- wheel setuptools >= 30.3.0 cmake >= 3.16 pip >= 10.0 pybind11[global] >= 2.6.0
```
For context …
=> remove pip as a build-system dependency in pyproject.toml

.github/workflows/build_cmake.yml, MANIFEST.in, setup.py
As suggested in #290
We will probably need to tweak setup.py (or a config) again once we try adding custom serde support, but for now we should clean this up.
=> remove unnecessary components from python wheel

common/include/memory_operations.hpp, python/CMakeLists.txt, python/datasketches/PySerDe.py, python/datasketches/__init__.py, python/include/py_serde.hpp, python/pybind11Path.cmd, python/src/__init__.py, python/src/datasketches.cpp, python/src/py_serde.cpp, python/src/vo_wrapper.cpp, python/tests/vo_test.py, sampling/include/var_opt_sketch.hpp, sampling/include/var_opt_sketch_impl.hpp, sampling/include/var_opt_union.hpp
The immediate result is for varopt, but having this working should be an important part of adding tuple support.
I'm least confident in the error recovery during deserialization. I think it's most likely that Python will throw an error which propagates through the c++ code. In this case I'm intercepting it to try to decrement reference counts for items we've already allocated but it's hard to tell if that's actually preventing a leak or not. Happy for suggestions on how to clean up that code.
Also, fixed a size bug in varopt.
=> Add python serde support for varopt sketches

fi/include/reverse_purge_hash_map_impl.hpp
I think reverse_purge_hash_map copy constructor should do this here, the original result is not being able to copy all the values. Or remove the if and copy all the values directly, but it may affect some performance
=> Update  reverse_purge_hash_map copy constructor

theta/include/theta_sketch_impl.hpp, tuple/include/tuple_sketch_impl.hpp
Based on #300 , we should avoid calling memcpy() when entries_ is empty to keep -fsanitize=undefiend happy. The sanitizer (reasonably) detected a copy of 0 bytes from nullptr. And while that should be completely harmless in this case, it's cleaner to avoid entirely.
=> avoid needless call to memcpy with an empty entries_ array

fi/include/frequent_items_sketch.hpp, fi/include/reverse_purge_hash_map.hpp
Noticed a couple broken links in the header documentation.  Small patch to update.
=> Fix broken links to reference Java files from before move to Apache.

python/src/cpc_wrapper.cpp, python/src/fi_wrapper.cpp, python/src/hll_wrapper.cpp, python/src/kll_wrapper.cpp, python/src/quantiles_wrapper.cpp, python/src/req_wrapper.cpp, python/src/theta_wrapper.cpp, python/src/vector_of_kll.cpp, python/src/vo_wrapper.cpp, python/tests/kll_test.py, python/tests/quantiles_test.py, python/tests/req_test.py, python/tests/theta_test.py, python/tests/vo_test.py
added iterators, rearranged and simplified existing code
=> Python wrapper improvement

sampling/include/var_opt_sketch_impl.hpp, sampling/test/var_opt_sketch_test.cpp, sampling/test/var_opt_union_test.cpp
These variables were never read, which causes warning when compiling with clang 16
=> Remove write-only variables

theta/include/theta_helpers.hpp
theta_helpers.hpp uses theta_constants::MAX_THETA, which is declared in theta_constants.hpp. This patch #includes it as well as alphabetizes the standard headers.
=> Include header implicitly used

theta/include/theta_helpers.hpp, theta/include/theta_sketch_impl.hpp, tuple/include/tuple_sketch_impl.hpp
In clang-16, there are warnings like this upon build:
warning: implicit conversion from 'const uint64_t' (aka 'const
unsigned long') to 'double' changes value from 9223372036854775807
to 9223372036854775808 [-Wimplicit-const-int-float-conversion]
Explicit casting fixes those warnings.
=> Explicitly cast constant uint64_ts that lose precision.

cpc/include/cpc_compressor_impl.hpp
uint8_t can never be < 0 so this addresses a warning from gcc.
=> Remove unsigned < 0 check

.github/workflows/build_wheels.yml
QEMU seems to be the standard way to build wheels for arm64/aarch64 (same thing) with github actions. Cross compilation doesn't seem to be supported by cibuildwheel currently. The drawback of QEMU is that it's very, very slow.
Also removed a config step by putting the logic into a more appropriate step's env variables.
Tested a reduced set of platforms with a single python version and verified that the .so produced reports back as the right file type. I don't have an AWS instance to test this on, so waiting for the result of testing in  #333 .  If that works, this should be good to merge (and then maybe back-port into the 4.0.x branch).
=> Build linux arm64/aarch64 wheels

NOTICE, cpc/include/cpc_compressor_impl.hpp, python/src/vector_of_kll.cpp
Fix warnings, bump copyright year
=> 4.0 cleanup

hll/include/hll.hpp
While I'm here, include \<string\>, which is needed in some of the APIs.
=> Fix doc strings in hll.hpp

common/include/MurmurHash3.h, cpc/include/cpc_util.hpp
. . . by removing one macro and prefacing the other with the logical module it's associated with.
=> Reduce likelihood of macro collision

sampling/include/var_opt_sketch_impl.hpp, sampling/include/var_opt_union.hpp, sampling/include/var_opt_union_impl.hpp
Tried to use a newer C++ standard and discovered varopt used deprecated allocator methods.  Those were relatively small, but I also discovered that the union didn't use the allocator properly at all.
=> use allocator properly in varopt union

kll/test/kll_sketch_test.cpp, quantiles/test/quantiles_sketch_test.cpp, sampling/include/var_opt_union_impl.hpp
Was playing with compiler warning flags and it pointed out that we were calling the integer abs() on float values, so I decided to ensure we're using std::abs() globally, even where we had fabs() before.
=> ensure we use std::abs() everywhere

python/CMakeLists.txt, python/datasketches/PySerDe.py, python/datasketches/TuplePolicy.py, python/datasketches/TupleWrapper.py, python/datasketches/__init__.py, python/include/tuple_policy.hpp, python/src/datasketches.cpp, python/src/py_serde.cpp, python/src/theta_wrapper.cpp, python/src/tuple_wrapper.cpp, python/tests/tuple_test.py, setup.py
This adds tuple sketch support to the python library, and specifically provides an arbitrary python object as the summary, as well as custom python policies for set operations.
A few basic policy implementations are included. They both demonstrate examples of how to implement a custom policy as well as provide a few basic options that seem reasonably useful.
And unlike the previous attempt, this has unit tests in place. And I hope somewhat improved documentation.
=> Python tuple sketch

fi/include/reverse_purge_hash_map.hpp, hll/include/HllArray-internal.hpp, hll/include/HllArray.hpp, hll/include/coupon_iterator-internal.hpp, hll/include/coupon_iterator.hpp, kll/include/kll_sketch.hpp, kll/include/kll_sketch_impl.hpp, quantiles/include/quantiles_sketch.hpp, quantiles/include/quantiles_sketch_impl.hpp, req/include/req_sketch.hpp, req/include/req_sketch_impl.hpp, sampling/include/var_opt_sketch.hpp, sampling/include/var_opt_sketch_impl.hpp, sampling/test/var_opt_sketch_test.cpp, theta/include/theta_update_sketch_base.hpp, theta/include/theta_update_sketch_base_impl.hpp
Not entirely confident on all the difference types, and I punted on the pointer type to a std::pair<> we return since I don't think it'll matter with how we use things.
Anyway, I don't expect this to be the final version but this does at least seem to work with both gcc and clang (14) for a few different c++ standards (11 and 20 at least)
=> Remove inheritance from std::iterator

python/include/py_object_ostream.hpp, python/include/tuple_policy.hpp, python/src/fi_wrapper.cpp, python/tests/fi_test.py
I'm very much torn on whether defining `operator<<` on py::object is a good idea, even with it static to limit the scope. The sketch's `to_string()` method won't work without that, though. Even this way, it requires there to be a `__str__()` method defined for the python class to work usefully.
Unless there's a better way the only alternatives are that we write a new `to_string()` for generic objects calling the method directly, write a version that can't list the objects, or remove that method entirely.
But this feels rather hacky so I'm open to suggestions.
=> Frequent items generic support

python/include/py_object_lt.hpp, python/include/quantile_conditional.hpp, python/src/kll_wrapper.cpp, python/src/quantiles_wrapper.cpp, python/src/req_wrapper.cpp, python/tests/kll_test.py, python/tests/quantiles_test.py, python/tests/req_test.py, quantiles/include/quantiles_sketch_impl.hpp
Our quantiles algorithms aren't the most compact, but they do benefit from being fully value-agnostic -- to the point where all we require is a less-than comparator. We've had support for generic items in Java and C++, and this should add it for python.
I had to change a couple uses of std::to_string() in the non-python legacy quantiles implementation to use the ostream operator. I believe this is safe and does not change the API since std::to_string() can't be overridden and the types for which it works also have an ostream operator defined. No need for a major version bump as a result of this PR.
=> Items support for quantile sketch family

common/include/common_defs.hpp
when using kll_sketch in parallel, it will use the same random engine, making TSAN complain:
```
WARNING: ThreadSanitizer: data race (pid=1760545)
Read of size 8 at 0x000032e79000 by thread T1097:
#0 std::__1::mersenne_twister_engine<unsigned long, 32ul, 624ul, 397ul, 31ul, 2567483615ul, 11ul, 4294967295ul, 7ul, 2636928640ul, 15ul, 4022730752ul, 18ul, 1812433253ul>::operator()() ~/ByConity/contrib/libcxx/include/random:2394:25 (clickhouse+0x1eb2bdb9) (BuildId: 76fc9d59c0dfa515)
#1 std::__1::independent_bits_engine<std::__1::mersenne_twister_engine<unsigned long, 32ul, 624ul, 397ul, 31ul, 2567483615ul, 11ul, 4294967295ul, 7ul, 2636928640ul, 15ul, 4022730752ul, 18ul, 1812433253ul>, 1ul, unsigned int>::__eval(std::__1::integral_constant<bool, true>) …
```
=> make random utils thread safe

theta/include/theta_union_base_impl.hpp, theta/include/theta_update_sketch_base_impl.hpp, theta/test/theta_union_test.cpp
=> theta union get_result() fix

hll/include/Hll4Array-internal.hpp, hll/include/Hll4Array.hpp, hll/include/Hll6Array-internal.hpp, hll/include/Hll6Array.hpp, hll/include/Hll8Array-internal.hpp, hll/include/Hll8Array.hpp, hll/include/HllArray-internal.hpp, hll/include/HllArray.hpp, hll/include/HllSketchImplFactory.hpp, hll/include/HllUnion-internal.hpp, hll/test/HllUnionTest.cpp
This changes HLL union to delay recomputing the KxQ and cur_min values until the union gadget needs to be made a consistent sketch (either get_result() or a direct get_estimate() will trigger that). This mirrors how HLL union operates in java.
Using characterization's hll-union-timing test on my linux desktop showed a steady-state merge speed improvement around 2.8x.
=> Hll delay kxq

python/src/cpc_wrapper.cpp, python/tests/cpc_test.py
We're using the CPC module from Python, and it's convenient to be able to call `get_lg_k` to see with what parameter a sketch was configured with. This PR exposes it via Python bindings.
=> Added get_lg_k to cpc's python wrapper

CODE_OF_CONDUCT.md, CONTRIBUTING.md
Adding code of conduct and contributing markdown as Gitbook's [Criteria for Open-Source Projects](https://docs.gitbook.com/account-management/plans/apply-for-the-non-profit-open-source-plan#criteria-for-open-source-projects) for new website experimentation.
=> Adding files required by gitbook

.github/workflows/build_cmake.yml, tuple/CMakeLists.txt
Addresses install issue reported by @c-dickens via slack.
No CI test added yet since I need to look at how to set that up. Currently just trying to un-break python.
=> fix install file list for array of doubles

density/include/density_sketch_impl.hpp
std::random_shuffle() is removed in c++17 so this ensures strict compatibility with the standard while still using a c++11-compatible method to achieve the same goal.
=> density sketch c++17 compatibility

cpc/include/cpc_compressor.hpp, cpc/include/cpc_compressor_impl.hpp
`std::atexit()` is apparently considered a legacy C thing since C++ should ideally be able to use static objects. Regardless, this worked to clean up: When I tested in valgrind we finally had a clean report for CPC for the first time ever.
=> register cpc teardown functions for std::atexit

sampling/include/ebpps_sample.hpp, sampling/include/ebpps_sample_impl.hpp, sampling/include/ebpps_sketch.hpp, sampling/include/ebpps_sketch_impl.hpp, sampling/test/ebpps_sample_test.cpp
Keeps a temporary sample of size 1 on-hand for updates/merges to avoid a new std::vector allocation of size 1 each time.  Local manual testing shows a fairly small but consistent benefit (0.1-0.3s out of an 8.4s run)
=> Ebpps speedup

common/include/MurmurHash3.h
This is a benign report. But clang-18 started to complain.
See https://github.com/ClickHouse/ClickHouse/issues/63858
=> Fix UBSan report while compiling with clang-18

filters/test/bloom_filter_deserialize_from_java_test.cpp, filters/test/bloom_filter_serialize_for_java.cpp
* fix type on num_hashes to uint16_t
* change bloom_filter_filter to bloom_filter::builder
Added corresponding tests in java and verified locally in both directions.
=> Fix cross-lang tests for Bloom filter

filters/include/bloom_filter.hpp, filters/include/bloom_filter_impl.hpp, tdigest/include/tdigest_impl.hpp
Trying to build python gives errors. Fixed by including in the wrapper itself, but our files shouldn't be missing needed headers.
=> add missing algorithm header

count/test/count_min_test.cpp
I noticed that this test
```cpp
TEST_CASE("CM parameter suggestions", "[error parameters]") {
// Bucket suggestions
REQUIRE_THROWS(count_min_sketch<uint64_t>::suggest_num_buckets(-1.0), "Confidence must be between 0 and 1.0 (inclusive)." );
//...
```
was still passing even though `suggest_num_buckets` throws the following error message: `"Relative error must be at least 0."` instead of `"Confidence must be between 0 and 1.0 (inclusive)."`.
This is because `REQUIRE_THROWS` doesn't check if the error message matches. 
`REQUIRE_THROWS_WITH` should be used instead.
=> Use REQUIRE_THROWS_WITH to check for error message
